// <auto-generated />
using System;
using ExamenApisApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenApisApp.Migrations
{
    [DbContext(typeof(Examen2Context))]
    partial class Examen2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExamenApisApp.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("idProducto");

                    b.Property<string>("Categoria")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("categoria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto")
                        .HasName("PK__producto__07F4A132DC0B02DD");

                    b.ToTable("producto", (string)null);

                    b.HasData(
                        new
                        {
                            IdProducto = 1,
                            Categoria = "Perfumes",
                            Descripcion = "Perfume con aroma a blueberry.",
                            Nombre = "BlueBerry Perfume",
                            Precio = 25m
                        },
                        new
                        {
                            IdProducto = 2,
                            Categoria = "Perfumes",
                            Descripcion = "Perfume con aroma a strawberry.",
                            Nombre = "Strawberry Perfume",
                            Precio = 30m
                        },
                        new
                        {
                            IdProducto = 3,
                            Categoria = "Perfumes",
                            Descripcion = "Perfume con aroma a cherry.",
                            Nombre = "Cherry Perfume",
                            Precio = 28m
                        },
                        new
                        {
                            IdProducto = 4,
                            Categoria = "Perfumes",
                            Descripcion = "Perfume florar, con notas de lavender.",
                            Nombre = "Lavender Perfume",
                            Precio = 30m
                        },
                        new
                        {
                            IdProducto = 5,
                            Categoria = "Skincare",
                            Descripcion = "Facial Cleanser con extractos de cucumber o roses.",
                            Nombre = "Facial Cleanser",
                            Precio = 50m
                        },
                        new
                        {
                            IdProducto = 6,
                            Categoria = "Skincare",
                            Descripcion = "Lip balm con extracto de rosas y miel.",
                            Nombre = "Lipbalm",
                            Precio = 15m
                        },
                        new
                        {
                            IdProducto = 7,
                            Categoria = "Skincare",
                            Descripcion = "Facial Scrub, deja tu piel suave.",
                            Nombre = "Facial Scrub",
                            Precio = 55m
                        },
                        new
                        {
                            IdProducto = 8,
                            Categoria = "Skincare",
                            Descripcion = "Toner, refresca y prepara la piel.",
                            Nombre = "Toner",
                            Precio = 48m
                        },
                        new
                        {
                            IdProducto = 9,
                            Categoria = "Skincare",
                            Descripcion = "Face Cream, hidrata y portege tu piel.",
                            Nombre = "Face Cream",
                            Precio = 52m
                        },
                        new
                        {
                            IdProducto = 10,
                            Categoria = "Make-up",
                            Descripcion = "Gloss, hidrata y pigmenta los labios.",
                            Nombre = "Gloss",
                            Precio = 22m
                        },
                        new
                        {
                            IdProducto = 11,
                            Categoria = "Make-up",
                            Descripcion = "Kit BT21, contiene una base de maquillage.",
                            Nombre = "Kit BT21",
                            Precio = 60m
                        },
                        new
                        {
                            IdProducto = 12,
                            Categoria = "Make-up",
                            Descripcion = "Blush, dale un color natural a tus mejillas.",
                            Nombre = "Kit BT21",
                            Precio = 26m
                        },
                        new
                        {
                            IdProducto = 13,
                            Categoria = "Make-up",
                            Descripcion = "Blush duo, duo de dos rubores.",
                            Nombre = "Blush duo",
                            Precio = 30m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
